FROM docker.io/eclipse-temurin:17-jre-centos7

USER root

RUN yum update -y && \
    yum install -y curl sudo tar && \
    yum clean all && rm -rf /var/lib/yum

WORKDIR /opt/jboss

ENV JAVA_HOME /opt/java/openjdk

ENV WILDFLY_VERSION 23.0.2.Final
ENV WILDFLY_SHA256 6525f6372a8dbddb84d7e3a466dbef1e046253c2bcd682c29fd0f4c1ec606fc4
ENV JBOSS_HOME /opt/jboss/wildfly

RUN cd /root \
    && curl -fLO https://github.com/wildfly/wildfly/releases/download/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.tar.gz || curl -fLO https://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.tar.gz \
    && sha256sum wildfly-$WILDFLY_VERSION.tar.gz | grep $WILDFLY_SHA256 \
    && tar xf wildfly-$WILDFLY_VERSION.tar.gz \
    && mv $HOME/wildfly-$WILDFLY_VERSION $JBOSS_HOME \
    && rm wildfly-$WILDFLY_VERSION.tar.gz

ENV LAUNCH_JBOSS_IN_BACKGROUND true

EXPOSE 8080
HEALTHCHECK --start-period=5m CMD curl --fail http://localhost:8080 || exit 1

ADD entrypoint.sh /
ADD start.sh /start.sh

ENV WILDFLY_USER_NAME jboss
ENV WILDFLY_GROUP_NAME jboss
ENV WILDFLY_USER_UID 1000 
ENV WILDFLY_GROUP_GID 1000 

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]
